<div>
    @livewire('home.culture-section')
    @livewire('home.routes-section')
    @livewire('home.visa-section')
    @livewire('home.guides-section')
    @livewire('home.testimonials-section')
    @livewire('home.about-section')
    @livewire('home.contact-section')   
</div>
